---

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: redhat.yml
  when: ansible_distribution == 'RedHat'


- name: installs 'docker-py'
  pip:
    name: docker-py

- name: adds 'docker' to start on boot
  service:
    name: docker
    enabled: yes

- name: creates docker service directory
  file:
    state: directory
    path: '/etc/systemd/system/docker.service.d/'


- set_fact:
    advertise_addr: '{{hostvars[inventory_hostname]["ansible_"+advertise_interface.replace("-","_")]["ipv4"]["address"]}}'
  when: advertise_interface is defined

- set_fact:
    advertise_addr: '{{ ansible_default_ipv4["address"] }}'
  when: advertise_interface is not defined


- name: creates docker configuration file
  template:
    src: 'docker.conf.j2'
    dest: '/etc/systemd/system/docker.service.d/docker.conf'
  notify:
    - 'daemon-reload'
    - 'restart docker'

- set_fact:
    cluster_ips: '{{ groups["cloud-node"] | map("extract", hostvars, ["ansible_"+advertise_interface.replace("-","_"), "ipv4", "address"]) | list }}'
  when: advertise_interface is defined

- set_fact:
    cluster_ips: '{{ groups["cloud-node"] | map("extract", hostvars, ["ansible_default_ipv4", "address"]) | list }}'
  when: advertise_interface is undefined


- name: allow access to Docker port from the cluster
  iptables:
    chain: INPUT
    source: "{{item}}"
    protocol: tcp
    destination_port: 2376
    jump: ACCEPT
  with_items: '{{cluster_ips}}'

- name: allow access to overlay control plane (tcp) from the cluster
  iptables:
    chain: INPUT
    source: "{{item}}"
    protocol: tcp
    destination_port: 7946
    jump: ACCEPT
  with_items: '{{cluster_ips}}'

- name: allow access to overlay control plane (udp) from the cluster
  iptables:
    chain: INPUT
    source: "{{item}}"
    protocol: udp
    destination_port: 7946
    jump: ACCEPT
  with_items: '{{cluster_ips}}'

- name: allow access to overlay data plane from the cluster
  iptables:
    chain: INPUT
    source: "{{item}}"
    protocol: udp
    destination_port: 4789
    jump: ACCEPT
  with_items: '{{cluster_ips}}'
